config/routes.rb
Rails.application.routes.draw do
  resources :repair_problems
  resources :repairs
  resources :problems
  resources :models
  resources :companies
  root 'repairs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/repair_problem.rb
class RepairProblem < ApplicationRecord
  belongs_to :repair
  belongs_to :problem
end

app/controllers/repair_problems_controller.rb
class RepairProblemsController < ApplicationController
  before_action :set_repair_problem, only: [:show, :edit, :update, :destroy]

  # GET /repair_problems
  # GET /repair_problems.json
  def index
    @repair_problems = RepairProblem.all
  end

  # GET /repair_problems/1
  # GET /repair_problems/1.json
  def show
  end

  # GET /repair_problems/new
  def new
    @repair_problem = RepairProblem.new
  end

  # GET /repair_problems/1/edit
  def edit
  end

  # POST /repair_problems
  # POST /repair_problems.json
  def create
    @repair_problem = RepairProblem.new(repair_problem_params)

    respond_to do |format|
      if @repair_problem.save
        format.html { redirect_to @repair_problem, notice: 'Repair problem was successfully created.' }
        format.json { render :show, status: :created, location: @repair_problem }
      else
        format.html { render :new }
        format.json { render json: @repair_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_problems/1
  # PATCH/PUT /repair_problems/1.json
  def update
    respond_to do |format|
      if @repair_problem.update(repair_problem_params)
        format.html { redirect_to @repair_problem, notice: 'Repair problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair_problem }
      else
        format.html { render :edit }
        format.json { render json: @repair_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_problems/1
  # DELETE /repair_problems/1.json
  def destroy
    @repair_problem.destroy
    respond_to do |format|
      format.html { redirect_to repair_problems_url, notice: 'Repair problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_problem
      @repair_problem = RepairProblem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_problem_params
      params.require(:repair_problem).permit(:repair_id, :problem_id)
    end
end

app/helpers/repair_problems_helper.rb
module RepairProblemsHelper
end

app/views/repair_problems/_form.html.erb
<%= simple_form_for(@repair_problem) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :repair %>
    <%= f.association :problem %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/repair_problems/edit.html.erb
<h1>Editing Repair Problem</h1>

<%= render 'form', repair_problem: @repair_problem %>

<%= link_to 'Show', @repair_problem %> |
<%= link_to 'Back', repair_problems_path %>

app/views/repair_problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repair Problems</h1>

<table>
  <thead>
    <tr>
      <th>Repair</th>
      <th>Problem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repair_problems.each do |repair_problem| %>
      <tr>
        <td><%= repair_problem.repair %></td>
        <td><%= repair_problem.problem %></td>
        <td><%= link_to 'Show', repair_problem %></td>
        <td><%= link_to 'Edit', edit_repair_problem_path(repair_problem) %></td>
        <td><%= link_to 'Destroy', repair_problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair Problem', new_repair_problem_path %>

app/views/repair_problems/new.html.erb
<h1>New Repair Problem</h1>

<%= render 'form', repair_problem: @repair_problem %>

<%= link_to 'Back', repair_problems_path %>

app/views/repair_problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Repair:</strong>
  <%= @repair_problem.repair %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @repair_problem.problem %>
</p>

<%= link_to 'Edit', edit_repair_problem_path(@repair_problem) %> |
<%= link_to 'Back', repair_problems_path %>