config/routes.rb
Rails.application.routes.draw do
  resources :repair_problems
  resources :repairs
  resources :problems
  resources :models
  resources :companies
  root 'repairs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/repair.rb
class Repair < ApplicationRecord
  belongs_to :model
  belongs_to :problem
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
    @company_id 
    @c=Company.all
    
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(repair_params)

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair }
      else
        format.html { render :edit }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url, notice: 'Repair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:model_id, :problem_id, :other, :pick_date)
    end
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/_form.html.erb
<%= simple_form_for(@repair) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.collection_select @company_id, @c, :company_id, :name, prompt: true %>
    <%= f.collection_select :model_id, Model.where("company_id = ?", @company_id), :model_id, :name, prompt: true %>
    <%= f.association :model %>
    <%= f.association :problem %>
    <%= f.input :other %>
    <%= f.input :pick_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<h1>Editing Repair</h1>

<%= render 'form', repair: @repair %>

<%= link_to 'Show', @repair %> |
<%= link_to 'Back', repairs_path %>

app/views/repairs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repairs</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Problem</th>
      <th>Other</th>
      <th>Pick date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= repair.model.name %></td>
        <td><%= repair.problem.issue %></td>
        <td><%= repair.other %></td>
        <td><%= repair.pick_date %></td>
        <td><%= link_to 'Show', repair %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair', new_repair_path %>

app/views/repairs/new.html.erb
<h1>New Repair</h1>

<%= render 'form', repair: @repair %>

<%= link_to 'Back', repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @repair.model.name %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @repair.problem.issue %>
</p>

<p>
  <strong>Other:</strong>
  <%= @repair.other %>
</p>

<p>
  <strong>Pick date:</strong>
  <%= @repair.pick_date %>
</p>

<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>